# -*- coding: utf-8 -*-
"""Ecommerce  Purchase Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uCAJtsNrTjIJJfYYdQr542TMpQvznEEV
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/Ecommerce Purchases')

"""Display rows of dataset"""

df.head()

"""Display last rows of the dataset"""

df.tail()

"""Check Datatype of each column"""

df.info()

"""Check the null value"""

df.isnull().count()

"""NUmber of rows and column"""

len(df.columns)

df.columns

df['Purchase Price'].max()

df['Purchase Price'].min()

"""Average Purchase Price"""

df['Purchase Price'].mean()

"""How many People have french as a language"""

df.columns

len(df[df['Language']=='fr'])

df['Language']=='fr'

df[df['Language']=='fr'].count()

"""Job title contains engineer"""

len(df[df['Job'].str.contains('engineer',case = False)])

df[df['IP Address'] == '132.207.160.22']['Email']

"""How many people have Master card as there credit card provider and made a purchase above 50?"""

df[(df['CC Provider'] == 'Mastercard') & (df['Purchase Price']>50)]

len(df[df['CC Exp Date'].apply(lambda X:X[3:] == '20')])

def fun():
  count = 0
  for date in df['CC Exp Date']:
    if date.split('/')[1] == '20':
      count = count+1
    print(count)

#  fun()

list1 = []
for email in df['Email']:
  email.split('@')

df['Email']

df['temp'].value_counts().head()

